NodeName=deep-gpu-10, AutoDetect=off Name=gpu Type=2080_ti File=/dev/nvidia[0-7]
NodeName=deep-gpu-11, AutoDetect=off Name=gpu Type=v100 File=/dev/nvidia[0-7]

NodeName=deep-chungus-1, AutoDetect=off Name=gpu Type=a100 File=/dev/nvidia[0-7]
NodeName=deep-chungus-[2-5], AutoDetect=off Name=gpu Type=a100 File=/dev/nvidia[0-8]

NodeName=deep-chungus-[7,9-11], AutoDetect=off Name=gpu Type=a100 File=/dev/nvidia[0-7]
NodeName=deep-chungus-8, AutoDetect=off Name=gpu Type=a100 File=/dev/nvidia[0-6]

#NodeName=deep-h-1, AutoDetect=off Name=gpu Type=h100 File=/dev/nvidia[0-1]
#NodeName=deep-h-1, AutoDetect=off Name=gpu Type=h100 File=/dev/nvidia[4-7]


NodeName=deep-h-[1-3], AutoDetect=off Name=gpu Type=h100 File=/dev/nvidia[0-7]
